### ISSUE TITLE
Future meetings

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-social-media#10]
@esraajb @Suuuuha @JWLD @mattlub and others...

Let's set meetings for April, May and June. Do you prefer lunchtime or evening (looks like Sunday or Tuesday could work)?

If we don't have anything up for discussion, we can decide not to meet - but having meetings on the calendar will allow those who want to participate to plan to attend.

**Comment by mattlub** [comment]
Hi- I personally would prefer a lunch time meeting.

**Comment by MohamedOmarii** [comment]
me too I would prefer lunchtime meeting

**Comment by rebeccaradding** [comment]
Great, any day of week preference? Let me know and I will add to calendar.

**Comment by MohamedOmarii** [comment]
in Wednesday is being good :+1:

**Comment by rebeccaradding** [comment]
We last met first Wednesday in March, so how about we do first Wednesday for April, May, and June?

**Comment by mattlub** [comment]
Wednesday 5th April is ok for me

**Comment by rebeccaradding** [comment]
Great I put the meeting on the Google calendar.
