### ISSUE TITLE
Combine Marketing and Outreach repos?

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-social-media#18]
While I think there is a distinction between marketing and outreach, our posts in these repos have become somewhat interchangeable, with our usage focused on the `outreach` repository.

@Suuuuha @HilbertSpitzer @esraajb @shiryz @Karyum @mattlub @m4v15 thoughts on whether we should consolidate, possibly by closing the marketing repo?

**Comment by mattlub** [comment]
@rebeccaradding I agree. If we do so then we need to update the outreach charter and readme.

**Comment by rebeccaradding** [comment]
@mattlub when task groups are introduced for Nazareth this week, they will likely include some formulation based on these: https://github.com/foundersandcoders/london-programme/issues/254

One task group is social media. I suggest we rename `nazareth-marketing` as `nazareth-social-media` and use it as a place for that task group to draft posts using photos/videos they take on behalf of the task group, which I would then post on social media.

This is what @AbdullahChaudhry and @rebecacalvoquintero are doing in London.

Thoughts?

**Comment by mattlub** [comment]
sure- how exactly are we planning on running biz dev in nazareth? It seems that it was slightly more regimented in London.

**Comment by rebeccaradding** [comment]
@mattlub @jsms90 @m4v15 @Suuuuha 

Would the four of you be available to discuss biz-dev, say, tomorrow or Thursday? I'd like to hear from Jen how the reformatting went in London and to put our heads together here about how to give FACN2 more specific remits that are appropriate to this context.

**Comment by rebeccaradding** [comment]
@mattlub I went ahead and did this in preparation for business development. Closing the issue!
