### ISSUE TITLE
Founders & Coders Instagram

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-social-media#2]
We already have an account - @founderscoders.

Waiting on @sofer for verification code to get access.

---

For discussion: How do we plan to use this account to increase expressions of interest in the application?

**Comment by rebeccaradding** [comment]
@shiryz will get login info from Sohil.

@Suuuuha @mattlub and @JWLD will maintain the account.

@esraajb will repost appropriate photos to the Nazareth FB page.

**Comment by rebeccaradding** [comment]
@shiryz can you post the login information here?

**Comment by shiryz** [comment]
founderscoders
We!0veToCode

**Comment by rebeccaradding** [comment]
@shiryz do you need a verification code to login?

**Comment by sohilpandya** [comment]
@shirzy I'd delete the password from this issue. Even though this repo is private, I don't recommend ever putting a password onto GitHub. 

I suggest we delete the comment and also change the password just as a precautionary measure.

**Comment by shiryz** [comment]
@sohilpandya deleted

**Comment by rebeccaradding** [comment]
@rebeccaradding will share an Instagram photo on FB and tell people to follow the page.

@esraajb will tell the FB group to follow the Instagram page.

@m4v15 and @Suuuuha will look into following other pages.

@m4v15 will publish on FAC and C4E Gitter channels.

**Comment by rebeccaradding** [comment]
Turns out you can't share an Instagram photo unless the pages are linked - so I downloaded the photo and uploaded it to a post, which you can see here: https://www.facebook.com/founderscodersnazareth/posts/1800729260245437

**Comment by Suuuuha** [comment]
@rebeccaradding i just linked the pages :)
