### ISSUE TITLE
Questions for student video

### ISSUE THREAD

**Issue by matthewdking** [foundersandcoders/nazareth-social-media#21]
The plan is to make a promotional video for Founders & Coders Nazareth. There are lots of videos about London but it would be good to show applicants what Nazareth is like as well! We plan to show the space in the video and ask students questions about the course and their time here.

Preliminary questions:
+ Why F&C?
+ Why Nazareth?
+ What do you like about Nazareth?
+ What is F&C to you?
+ What was enjoyable moment on the course?
+ What is a typical day like at F&C?
+ What social activities do you do after class?
+ What have you gained from being on F&C? (not just technical)

Thoughts so far? If you have any questions to add please comment.

**Comment by shiryz** [comment]
I like the idea, my thinking around this is to 
- make it short and "snappy" as in move between frames quickly and don't focus on one answer for too long.
- Don't ask the questions during the video, ask the person who you're shooting to say it in the beginning, for example: "What I like about fac is..."
- Tell them not to use fac and instead say founders and coders.

**Comment by rebeccaradding** [comment]
@matthewdking if you recorded footage for one video with all the questions, then you could also cut 20-30 second clips where several people only answer one question. Does that make sense?

**Comment by matthewdking** [comment]
@rebeccaradding I think that is the general plan lots of short clips with answers. Probably quite a short video but will ideally show what its like to be a part of FAC Nazareth.

@shiryz good points I will make sure we try to get people to say the question at the start rather than ask the questions to the students.

Does anyone have any questions to add?

**Comment by yvonne-liu** [comment]
Some ideas: 
- Find a way to showcase diversity - I know London already did the "describe FAC in one word" in different languages, but I still think it's a very creative way of showcasing diversity -- could have short segments of current students saying where they're from!
- Having Arabic and Hebrew answers with subtitles 
- Adding to @shiryz's suggestion, you can also just have the question displayed on screen as well without having to say it: 

![screen shot 2017-08-09 at 12 19 25 pm](https://user-images.githubusercontent.com/22013117/29114440-04a243b2-7cfd-11e7-8561-7e2d5a6ce544.png)

**Comment by paulhanna1933** [comment]
Additional question: 
1) What plans do you have for after FAC?
