### ISSUE TITLE
Marketing Coding for Everyone

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-social-media#3]
In London, we use www.meetup.com to coordinate Coding for Everyone. We generally haven't advertised on Facebook.

In Nazareth, we have not used meetup.com, as it's an unfamiliar platform in the region. We created an event for the first Coding for Everyone meetup. We are also in the process of making an ad that announces our meetup happens every Monday.

How should we advertise future meetups, so that people know they happen every week, and creating events is not too much work for us?

**Comment by rebeccaradding** [comment]
@mattlub @m4v15 will investigate the best way of mass inviting people.

**Comment by m4v15** [comment]
shallow investigating seems to imply a group is better at promoting events than a page, but I will look into further: http://thesocialskinny.com/facebook-page-vs-group-a-facebook-marketing-dilemma/

**Comment by rebeccaradding** [comment]
@m4v15 good shout, perhaps we should make a C4E group and promote the event there each week so people can self-add if they are coming?
