### ISSUE TITLE
Medium Account

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-social-media#6]
@hibaakel has proposed writing a Medium article in Arabic about the Nazareth programme. 

@edgarfinn @m4v15 @jackcarlisle have proposed other ideas for English language articles about Nazareth. 

It appears we have an @founderscoders account, but I do not have the login info.

@sofer can you please supply info so that when they are ready to post we can use the FAC page?

Also, the description of the FAC page should be updated to reflect that we have two campuses.

**Comment by oliverjam** [comment]
This is probably good timing as @ConchobarMacNessa and I were just talking about setting up/finding an existing Medium account to use for the London blog posts.

Are we going to separate the marketing for the two cohorts or should we be posting all the articles under the same account? I know FreeCodeCamp use a Medium Publication to group together all their different articles written by different people, so that could be one option.

This route would allow us to potentially have future contributions from alumni or even people outside of F&C.

**Comment by mattlub** [comment]
any developments on this?

**Comment by rebeccaradding** [comment]
Hey @mattlub, I believe @katpas transferred ownership to the FAC twitter account - Kat, is that correct?

I'll get this sorted this week.

**Comment by sofer** [comment]
@rebeccaradding that is correct. If you have our twitter login, you can access our medium account.

**Comment by katpas** [comment]
@rebeccaradding yep, all access passed over to the founders & coders twitter account.

**Comment by rebeccaradding** [comment]
@mattlub I have the twitter info. Let's discuss some posts at the April meeting.

**Comment by mattlub** [comment]
@hibaakel @edgarfinn @m4v15 @JWLD anyone had any further thoughts on medium articles? We have a meeting discussing things tomorrow.

**Comment by rebeccaradding** [comment]
@JWLD wants to write about what it's like to do the course in Nazareth, as an international student, in a cross-cultural environment. 

**Action:** @JWLD will lead effort to put together notes/draft for an article by end of reading week to send to @rebeccaradding.

**Comment by m4v15** [comment]
@JWLD I wrote an email to an interested student that talks about our life in Nazareth/the course in general, I'll forward it on to you if you wanna lift some stuff from it

**Comment by JWLD** [comment]
That would be great, thanks

**Comment by rebeccaradding** [comment]
@JWLD touching base to see if you have a draft/some notes for the article.

**Comment by sofer** [comment]
Just to confirm that our publication page is at https://medium.com/founders-coders and is in need of some love ❤️

**Comment by JWLD** [comment]
Here's a draft I've been working on: https://medium.com/@jackwldavies/founders-and-coders-nazareth-life-as-an-international-student-c2be76fb161d

Apologies for the delay. Please feel free to tear into it and leave notes etc. - the more feedback the better!

**Comment by rebeccaradding** [comment]
@JWLD thank you SO much for writing this! 

I've left a couple of corrections and a few comments/suggestions. Overall, I think it's fantastic, and I would love to get it published in the next couple of days, in time to share with the current application pool.

**Comment by JWLD** [comment]
Thanks @rebeccaradding ! I've made some changes, see what you think :)

**Comment by rebeccaradding** [comment]
@JWLD very happy with this, ready to publish if you are!

**Comment by JWLD** [comment]
Published! I believe the FAC publication page has to invite me in order to include it there.

**Comment by rebeccaradding** [comment]
@JWLD is it possible you have to request to be included? I don't see an option to invite you.

**Comment by JWLD** [comment]
Here's the published link: https://medium.com/@jackwldavies/founders-and-coders-nazareth-life-as-an-international-student-c2be76fb161d

**Comment by rebeccaradding** [comment]
@JWLD just sent you a request!

**Comment by JWLD** [comment]
Hmm I can't see anything yet, did you follow these steps? https://help.medium.com/hc/en-us/articles/115004848868-Request-post-for-publication

**Comment by rebeccaradding** [comment]
@JWLD yep, it tells me now that I have pending request. Check again?

**Comment by JWLD** [comment]
I had my email prefs locked down quite tightly, maybe that blocked the request. I've changed it now - is it possible to re-send?

**Comment by JWLD** [comment]
Another option might be to [add me as a writer](https://medium.com/@aytekintank/how-to-add-someone-as-writer-on-medium-215f0ef6117c) and then I could submit the story myself

**Comment by rebeccaradding** [comment]
@JWLD I've just added you as an editor and as a writer.

**Comment by JWLD** [comment]
Great thanks, all done :)
