### ISSUE TITLE
Social Media Strategy

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-social-media#8]
### HISTORY

Prior to opening FAC Nazareth, Founders & Coders had one Facebook page and one Twitter account, which are linked. Facebook was used rarely, Twitter more often. 

When we began promoting the Nazareth programme, we updated the Facebook page and began posting regularly, about both Nazareth and London. We have also used Twitter for some Nazareth related posts.

In order to place a Facebook ad for the previous recruitment round, Afifi created a FAC Nazareth Facebook page. Although this page has been basically empty for two months, it has generated 350+ likes, climbing rapidly since the launch event.

### WHY

As we begin recruitment for the second course, as well as advertising for Coding for Everyone, we need a clear social media strategy for Founders & Coders Nazareth, which includes deciding which Facebook page to use as our central recruitment channel.

### WHAT

We will use _Founders & Coders Nazareth_ for promoting the Nazareth programme. This includes:

- Advertisements for the application
- Creating Coding for Everyone events
- Photos of course highlights 
- Links to press coverage
- Posts about other local events 
- Responding to messages 

Serene Afifi will continue to be an a page admin and will be permitted to place ads on behalf of the programme.

In addition, we will create a Founders & Coders _Instagram_ page and link it to the FAC Nazareth FB page. 

The _Founders & Coders_ Facebook page will continue to post about the Nazareth programme, primarily by highlighting press coverage and other newsworthy links.

### HOW

The Marketing Committee (currently @esraajb @shiryz @Suuuuha @mattlub @JWLD) 
will manage the FAC Nazareth page and Instagram account with support from @rebeccaradding.

Our first action step is to generate more likes for the page from the relevant local community. Marketing Committee will set next action steps!

**Comment by Jbarget** [comment]
see https://github.com/foundersandcoders/nazareth-programme/issues/97#issuecomment-291170217 for an idea of what london's social media are going to start putting out
